// Mocks generated by Mockito 5.4.6 from annotations
// in flower_tracking_app/test/modules/thanks_page/ui/thanks_page_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:ui' as _i7;

import 'package:flower_tracking_app/modules/home/domain/use_cases/get_pending_orders_use_case.dart'
    as _i2;
import 'package:flower_tracking_app/modules/home/ui/cubit/pending_orders/pending_orders_cubit.dart'
    as _i8;
import 'package:flower_tracking_app/modules/home/ui/cubit/pending_orders/pending_orders_state.dart'
    as _i3;
import 'package:flower_tracking_app/shared_layers/localization/l10n_manager/localization_manager.dart'
    as _i4;
import 'package:flutter_bloc/flutter_bloc.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetPendingOrdersUseCase_0 extends _i1.SmartFake
    implements _i2.GetPendingOrdersUseCase {
  _FakeGetPendingOrdersUseCase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeOrdersState_1 extends _i1.SmartFake implements _i3.OrdersState {
  _FakeOrdersState_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalizationManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalizationManager extends _i1.Mock
    implements _i4.LocalizationManager {
  MockLocalizationManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get currentLocale =>
      (super.noSuchMethod(
            Invocation.getter(#currentLocale),
            returnValue: _i5.dummyValue<String>(
              this,
              Invocation.getter(#currentLocale),
            ),
          )
          as String);

  @override
  bool get isEnglish =>
      (super.noSuchMethod(Invocation.getter(#isEnglish), returnValue: false)
          as bool);

  @override
  set currentLocale(String? _currentLocale) => super.noSuchMethod(
    Invocation.setter(#currentLocale, _currentLocale),
    returnValueForMissingStub: null,
  );

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i6.Future<void> changeLocal(String? languageCode) =>
      (super.noSuchMethod(
            Invocation.method(#changeLocal, [languageCode]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<String?> getSavedLocal() =>
      (super.noSuchMethod(
            Invocation.method(#getSavedLocal, []),
            returnValue: _i6.Future<String?>.value(),
          )
          as _i6.Future<String?>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [OrdersCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockOrdersCubit extends _i1.Mock implements _i8.OrdersCubit {
  MockOrdersCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.GetPendingOrdersUseCase get useCase =>
      (super.noSuchMethod(
            Invocation.getter(#useCase),
            returnValue: _FakeGetPendingOrdersUseCase_0(
              this,
              Invocation.getter(#useCase),
            ),
          )
          as _i2.GetPendingOrdersUseCase);

  @override
  _i3.OrdersState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeOrdersState_1(this, Invocation.getter(#state)),
          )
          as _i3.OrdersState);

  @override
  _i6.Stream<_i3.OrdersState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i3.OrdersState>.empty(),
          )
          as _i6.Stream<_i3.OrdersState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> doIntent(_i3.OrdersIntent? intent) =>
      (super.noSuchMethod(
            Invocation.method(#doIntent, [intent]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  dynamic removeOrder(String? orderId) =>
      super.noSuchMethod(Invocation.method(#removeOrder, [orderId]));

  @override
  void emit(_i3.OrdersState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i9.Change<_i3.OrdersState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}
