name: Code Check By Dart Linter (on Push or PR)
on:
  push:
    branches:
      - '**'
  pull_request:
    types: [opened, edited]
    branches:
      - '**'
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'

      - name: Print Dart and Flutter versions
        run: |
          dart --version
          flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Format code
        run: dart format .

      - name: Get current branch name
        id: get_branch
        run: echo "branch_name=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Apply Dart formatting changes"
          git push https://MoK369:${{ secrets.PAT }}@github.com/Team5-Projects-Advanced-Flutter-Elevate/flower_tracking_app.git HEAD:${{ env.branch_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
